# Generated by Django 5.2 on 2026-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='TodayDish',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breakfast', models.CharField(max_length=200)),
                ('breakfast_time', models.CharField(max_length=50)),
                ('lunch', models.CharField(max_length=200)),
                ('lunch_time', models.CharField(max_length=50)),
                ('dinner', models.CharField(max_length=200)),
                ('dinner_time', models.CharField(max_length=50)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
