# Generated by Django 5.2 on 2026-09-08 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_foodsafetycomplaint'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetycomplaint',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='food_safety/'),
        ),
    ]
