# Generated by Django 5.2 on 2026-09-13 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_foodsafetycomplaint_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetails',
            name='branch_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userdetails',
            name='hostel_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
