# Generated by Django 5.2 on 2026-09-13 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_complaint_branch_name_complaint_hostel_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='foodsafetycomplaint',
            name='branch_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='foodsafetycomplaint',
            name='hostel_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
