# Generated by Django 5.2 on 2026-09-13 14:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_foodsafetycomplaint_branch_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodSafetyVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=100)),
                ('hostel_name', models.CharField(max_length=100)),
                ('branch_name', models.CharField(max_length=100)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('complaint', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.foodsafetycomplaint')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.userdetails')),
            ],
            options={
                'unique_together': {('complaint', 'student')},
            },
        ),
    ]
