# Generated by Django 5.2 on 2026-09-17 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_foodsafetyvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='branch_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='feedback',
            name='hostel_name',
            field=models.CharField(default='Unknown', max_length=100),
            preserve_default=False,
        ),
    ]
